version: '3.5'

x-browserstack-creds-enviroment:
  &browserstack-creds-enviroment
  BROWSERSTACK_USERNAME: ""
  BROWSERSTACK_ACCESS_KEY: ""

x-pytest-config-environment:
  &pytest-config-environment
  TESTS_DIR: /app/tests

x-service-config-environment:
  &service-config-environment
  WHISK_CLIENT_ID: "WCqJWnpNatcf3LUCxZmq94pR30sj2OOdBbMoGO8NGrMgUMk6Ogl4EMvLqcykNuGf"
  WEB_DRIVER_NAME: "remote"


services:
  testing:
    environment:
      <<: *browserstack-creds-enviroment
      <<: *pytest-config-environment
      <<: *service-config-environment
    build: .
    image: vasilyevaa/whisk-test-assignment
    volumes:
      - './:/app'
    stdin_open: true
    tty: true

  allure:
    image: solutis/allure
    volumes:
      - './:/home/allure/'
    command: 'allure generate'
